
#mysql
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/board
    username: root
    password: wagle12#
  jpa:
    properties:
      hibernate:
        format_sql: true # ???? ??? ??? ???
        show_sql: true # ??? ??

mybatis:
  mapper-locations:classpath:com.fastcampus.boardserver.mapper/*.xml

logging:
  level:
    wagle: debug
    web: debug

