#mysql
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/board
    username: root
    password: wagle12#
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false
logging:
  level:
    wagle: debug
    web: debug

expire:
  defaultTime: 3600 #1?

mybatis:
  mapper-locations:classpath:com.fastcampus.boardserver.mapper/*.xml



